name: Django EC2 Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ci:
    name: 'Django CI'
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: create .env file
      run: |
        touch .env
        echo "${{ secrets.ENV }}" >> .env   
        
    - name: Run Tests
      run: |
        python manage.py test
  
  cd:
    name: 'Django CD'
    needs: ci
    runs-on: ubuntu-latest
    steps:
    - name: EC2 ssh connection test
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.UNO_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.UNO_PEM }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          sudo apt-get update
          sudo apt-get upgrade    
          cd /home/ubuntu/django-github-action
          source venv/bin/activate
          git pull
          pip install -r requirements.txt
          python manage.py migrate
          sudo lsof -t -i tcp:8000 | xargs kill -9
          nohup python manage.py runserver 0.0.0.0:8000 &
          # python manage.py runserver 0.0.0.0:8000
          exit
          echo "test success"
